### ISSUE TITLE
should Gratipay leave?

### ISSUE THREAD

**Issue by whit537** [opencompany/www.opencompany.org#159]
I helped start the OCI, but I and my company have gotten a lot of bad press this past year. Am I too much of a liability at this point? I'm willing to step away from the group and let others run with it if that's the best decision for OCI.

Anyone feel me on this?

**Comment by tenkabuto** [comment]
I see you and Gratipay as strong assets to the OCI, and I don't want you to leave. It's true that there's been bad press, but people who'll be swayed from their principles by the prospect of bad press are the true liabilities. I appreciate that you've been open to discussing your ideas and beliefs, especially with people that disagree with you, and the OCI would benefit from having more of that, not less.

That said, I don't know how the OCI will overcome the sense that there are mere shows of openness, where some issue is brought up by you or other company leaders and, despite differing viewpoints being brought up by contributors, the issue is resolved in a manner that doesn't differ much from the leaders' offered solutions. This is a concern of mine in light of the 8chan/Gratipay discussion (https://github.com/gratipay/inside.gratipay.com/issues/118), though I agreed with your decision.

When such 'shows' arise, the mental model of an Open Company as a business equivalent of an open source project (which I've been working with) fails, as it's much more difficult to fork a business. Providing a better model would help with this, though, but that can be addressed at a different time.

**Comment by kyledrake** [comment]
I agree with @tenkabuto. I do not believe you should step down from the OCI, nor do I want you to.

The openness of these controversies, and the reaction and response to how they have been handled, has been a valuable resource to learn and understand an ambiguous problem that is clearly a substantial risk factor to a growing company: the social defensibility of tolerance towards controversial speech. This is a problem that all companies that provide services to the public internet invariably have to face, and future companies will be able to stand on what has been discovered here, when their time comes and a crisis arrives, uninvited and unexpected, to their own front door.

The difference is that we now have documentation of each other's experiences to stand on. This more than anything demonstrates why the idea of an Open Company is so important.

I'll understand if you want to, but please don't leave.

**Comment by whit537** [comment]
Thanks for the vote of confidence @tenkabuto @kyledrake. I guess I'll go ahead and close this. If anyone feel differently please comment/reopen.
