### ISSUE TITLE
OpenCompany as a Team on Gratipay?

### ISSUE THREAD

**Issue by galuszkak** [opencompany/www.opencompany.org#164]
Gratipay is after major transition.

@whit537 you probably are best to tackle what we have to do now ;). Because now I'm not too much into Gratipay, so I'm not sure what is status of Open Company on Gratipay?

**Comment by whit537** [comment]
I'm not sure of the status of OCI at all. :-)

We should have a pow-wow, including you, me, @timothyfcook, and whomever else cares. We have a few grand and the beginnings of a brand here. Who wants it? :-)

I kind of want to hand off OCI to you, @galuszkak, and maybe @waldyrious. Do you want it?

**Comment by galuszkak** [comment]
I have to think about it. As you see I didn't have too much time last couple months to tackle in many things in Open Company. I still even didn't have time to send those t-shirts and stickers (they are laying in my room waiting for me to send to you guys).
I think @waldyrious will be great for moving things. He even work still on #103 . He's list is up to date here: https://github.com/waldyrious/awesome-open-company (last update 3 days ago).

**Comment by timothyfcook** [comment]
Especially given the new focus on Gratipay as a platform to support open teams (and open companies), I think this initiative is more important than ever and the success of the two projects might be intertwined.

**Comment by whit537** [comment]
@timothyfcook Could be. I see an overlap in what OCI and Gratipay are trying to accomplish, especially with Gratipay 2.0. I think of OCI as "unbound" and Gratipay as "bound." OCI has a loose definition of what an open company is, and Gratipay now has a strict definition: [open work](https://gratipay.com/about/#open-work) with [take-what-you-want payroll](https://gratipay.com/about/features/payroll). I'm finding myself in a conflict of interest in that I want to recruit companies to use Gratipay, not simply to join OCI.

I think we should basically let @waldyrious take the OCI and use it for the community-managed list of open companies and resources that he's got going. Would you be interested in that, @waldyrious?

**Comment by waldyrious** [comment]
Sorry for the delay, I've was away for the weekend. I would love to be part of the team maintaining the OCI, but I am not sure what is required/expected from that. Are you still planning to keep the summits going? Is shipping and re-stocking of t-shirts, stickers, etc. involved?

Considering that I am based in Portugal, and in the final months of my PhD, I believe the only reasonable commitment I can take right now is to help maintaining the website working and up-to-date. Here are some possible paths forward:

- Of course, I would prefer if a wiki-like approach was made part of the OCI, i.e. not making it an absolute requirement for companies to actively take the OCI pledge, thus allowing anyone to expand the list as long as there's evidence of them adhering to a close-enough approximation of the pledge. This could be achieved, e.g. by moving [awesome-open-company](https://github.com/waldyrious/awesome-open-company) to a page in opencompany.org, editable through PRs. We could somehow distinguish companies that explicitly adhered to the Initiative by adding an extra mark/badge to their entry, and perhaps providing a badge for them to use in their own website if they so choose.
- Otherwise, I would keep my repo active, but perhaps we could move it to the opencompany github organization.
- A third option, if you want to reduce the complexity/scope of the OCI, is converting the whole site/initiative to a simple (perhaps even single-page) website, which would essentially be a nicely-presented, html version of the awesome-open-company document (and still editable by anyone, through PRs).

Let me know if any of these ideas match what you guys have in mind, or what you'd suggest instead.

**Comment by whit537** [comment]
> A third option, if you want to reduce the complexity/scope of the OCI, is converting the whole site/initiative to a simple (perhaps even single-page) website, which would essentially be a nicely-presented, html version of the awesome-open-company document (and still editable by anyone, through PRs).

+1

The inclusion guidelines look good to me.

**Comment by whit537** [comment]
I've reticketed Option 3 as #166.

**Comment by mattbk** [comment]
Just a note here that http://www.opencompany.org/about/ still says it is funded on Gratipay and links to https://gratipay.com/~OpenCompany/, which is not a Gratipay Team and therefore can't accept donations on the platform.

**Comment by davidak** [comment]
Gratipay shut down in 2017. Consider using the fork Liberapay: https://github.com/opencompany/www.opencompany.org/issues/175

**Comment by chadwhitacre** [comment]
Bump to close.

**Comment by waldyrious** [comment]
Thanks for the heads-up, @chadwhitacre. I'll close this as deprecated/superseded by #175.
